env:
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  no-console:
    - warn
  indent:
    - off
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-explicit-any:
    - 0
  no-mixed-spaces-and-tabs:
    - 0
  no-inline-comments:
    - 2
